[package]
name = "desktop-capture"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color = { path = "../color" }
dxgcap = "0.2.4"
simple-error = "0.2.3"